export const STATUS = {
    UNKNOWN: "UNKNOWN",
    QUEUED: "QUEUED",
    WORKING: "WORKING",
    SUCCESS: "SUCCESS",
    FAILURE: "FAILURE",
    ERROR: "ERROR",
    TIMEOUT: "TIMEOUT",
    CANCELLED: "CANCELLED"
  };